prompt = 'Enter the file name to store data: ';
str = input(prompt,'s');
load(str);
%% variables used
% 'Node','percentage','prob','l','time',...
% 'dest_it','add_it','emergency','cov_it','Dcov_it','Acov_it','par_it','Dpar_it','Apar_it',...
% 'dest_val','cov_val','par_val','Dcov_val','Dpar_val','Acov_val','Apar_val',...
% 'tag_l','ener_l','role_l','tag_d','ener_d','role_d',...
% 'Atag_l','Aener_l','Arole_l','Atag_d','Aener_d','Arole_d',...
% 'Dtag_l','Dener_l','Drole_l','Dtag_d','Dener_d','Drole_d'

%% 
